#pragma once

#include "html_element.hpp"
#include "a.hpp"

MAKE_HTML_TAG(abbr)
MAKE_HTML_TAG(b)
MAKE_HTML_TAG(bdi)
MAKE_HTML_TAG(bdo)
MAKE_HTML_TAG(br)
MAKE_HTML_TAG(cite)
MAKE_HTML_TAG(code)
MAKE_HTML_TAG(data)
MAKE_HTML_TAG(dfn)
MAKE_HTML_TAG(em)
MAKE_HTML_TAG(i)
MAKE_HTML_TAG(kbd)
MAKE_HTML_TAG(mark)
MAKE_HTML_TAG(q)
MAKE_HTML_TAG(rb)
MAKE_HTML_TAG(rp)
MAKE_HTML_TAG(rt)
MAKE_HTML_TAG(rtc)
MAKE_HTML_TAG(ruby)
MAKE_HTML_TAG(s)
MAKE_HTML_TAG(samp)
MAKE_HTML_TAG(small)
MAKE_HTML_TAG(span)
MAKE_HTML_TAG(strong)
MAKE_HTML_TAG(sub)
MAKE_HTML_TAG(sup)
MAKE_HTML_TAG(time)
MAKE_HTML_TAG(u)
MAKE_HTML_TAG(var)
MAKE_HTML_TAG(wbr)